version: 0.2
phases:
  install:
    runtime-versions:
      java: coreetto13
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
artifacts:
  files:
    - target/deliziahr-authentication-service-0.0.1-SNAPSHOT.jar
